import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { roboto } from "@/components/ui/fonts";

export const metadata: Metadata = {
  title: {
    template: "Cakeify | %s",
    default: "Cakeify"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
